server:
  port: 8080

spring:
  application:
    name: MyBatisPlus_demo
  datasource:
    username: root
    password: 114514
    url: jdbc:mysql://localhost:3306/brand_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

# 设置控制台输出sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置下划线转驼峰命名
    map-underscore-to-camel: true

  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

